# zsoelim
# Autogenerated from man page /nix/store/26g7nm0ps69xdyn1am9rmvrfg2zkkbmg-man-db-2.10.2/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible -d 'This flag is available for compatibility with other  soelim programs'
complete -c zsoelim -s h -l help -d 'Print a help message and exit'
complete -c zsoelim -s V -l version -d 'Display version information'

